# Generated by Django 4.2.6 on 2023-11-02 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('avatar', models.ImageField(blank=True, default='/static/avatar/avatar.jpg', help_text='Изображение пользователя', null=True, upload_to=profiles.models.rename_image, verbose_name='Аватарка')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('bio', models.CharField(blank=True, max_length=1024, null=True, verbose_name='О себе')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[('MALE', 'Мужчина'), ('FEMALE', 'Женщина')], help_text='Пол пользователя', null=True, verbose_name='Пол')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телеграм')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
