# Generated by Django 4.2.7 on 2023-11-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Мужчина'), (2, 'Женщина')], help_text='Пол пользователя', null=True, verbose_name='Пол'),
        ),
    ]
