# Generated by Django 4.2.7 on 2023-11-19 16:32

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Изображение пользователя', null=True, upload_to=profiles.models.rename_image, verbose_name='Аватарка'),
        ),
    ]
