# Generated by Django 4.2.6 on 2023-10-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='The email must be unique', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
