# Generated by Django 4.2.6 on 2023-11-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Электронная почта должна быть уникальной', max_length=100, unique=True, verbose_name='Электронная почта'),
        ),
    ]
